# Generated by Django 4.2.3 on 2023-07-18 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_product_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_mame',
            new_name='product_name',
        ),
    ]
